version: '3'
services:
  apache:
    image: ghcr.io/logan-audic/apache
    ports:
      - "80:80"
    networks:
      - web
    volumes:
      - /srv/page/:/var/www/html/

    deploy:
      mode: replicated
      replicas: 1



  wordpress:
    image: ghcr.io/logan-audic/wordpress
    volumes:
      - /srv/docker_swarm/configuration/wordpress/:/var/www/html/index.html
      - /srv/docker_swarm/configuration/mysql/:/var/lib/mysql
    networks:
      - web
    deploy:
      mode: replicated
      replicas: 1

  mysql:
    image: ghcr.io/logan-audic/mysql
    ports:
      - "3306:3306"
    volumes:
      - /srv/docker_swarm/configuration/mysql/:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_db
      - MYSQL_USER=user_db
      - MYSQL_PASSWORD=user_db
      - MYSQL_DATABASE=mysql_db
    networks:
      - web
    deploy:
      mode: replicated
      replicas: 1

networks:
  web:
    driver: overlay
    external: false